// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.Migrations
{
    [DbContext(typeof(MainDBContext))]
    partial class MainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Astronaut", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INT");

                    b.Property<int>("FlightHours")
                        .HasColumnType("int");

                    b.Property<string>("Paygrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Astronauts", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FlightHours = 1200,
                            Paygrade = "A1",
                            Rank = "Commander"
                        },
                        new
                        {
                            ID = 2,
                            FlightHours = 900,
                            Paygrade = "A2",
                            Rank = "Pilot"
                        },
                        new
                        {
                            ID = 3,
                            FlightHours = 700,
                            Paygrade = "A3",
                            Rank = "Specialist"
                        });
                });

            modelBuilder.Entity("CelestialBody", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("FK_ParentPlanetID")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Name");

                    b.Property<string>("PlanetType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("ID");

                    b.HasIndex("FK_ParentPlanetID");

                    b.ToTable("CelestialBodies", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BodyType = "Planet",
                            Distance = 0m,
                            Name = "Earth",
                            PlanetType = "Rocky"
                        },
                        new
                        {
                            ID = 2,
                            BodyType = "Planet",
                            Distance = 225000000m,
                            Name = "Mars",
                            PlanetType = "Rocky"
                        },
                        new
                        {
                            ID = 3,
                            BodyType = "Moon",
                            Distance = 384400m,
                            FK_ParentPlanetID = 1,
                            Name = "Moon",
                            PlanetType = "Rocky"
                        });
                });

            modelBuilder.Entity("Crew", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Crews", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1
                        },
                        new
                        {
                            ID = 2
                        });
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FK_managerID")
                        .HasColumnType("INT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("ID");

                    b.HasIndex("FK_managerID");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("INT");

                    b.Property<int?>("FK_DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("DATE");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Emplyees", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FullName = "Neil Armstrong",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 2,
                            FullName = "Buzz Aldrin",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 3,
                            FullName = "Sally Ride",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 4,
                            FullName = "Carl Sagan",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 5,
                            FullName = "Jane Foster",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 6,
                            FullName = "Alice Johnson",
                            HireDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            ID = 7,
                            FullName = "Bob Smith",
                            HireDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("Joint_Astronaut_Crew", b =>
                {
                    b.Property<int>("CrewID")
                        .HasColumnType("INT");

                    b.Property<int>("AstronautID")
                        .HasColumnType("INT");

                    b.HasKey("CrewID");

                    b.HasIndex("AstronautID");

                    b.ToTable("JointAstronautCrews");
                });

            modelBuilder.Entity("Joint_Scientist_Mission", b =>
                {
                    b.Property<int>("MissionID")
                        .HasColumnType("INT");

                    b.Property<int>("ScientistID")
                        .HasColumnType("INT");

                    b.HasKey("MissionID");

                    b.HasIndex("ScientistID");

                    b.ToTable("JointScientistMissions");

                    b.HasData(
                        new
                        {
                            MissionID = 1,
                            ScientistID = 4
                        },
                        new
                        {
                            MissionID = 2,
                            ScientistID = 5
                        });
                });

            modelBuilder.Entity("Launchpad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("MaxSupportedWeight")
                        .HasColumnType("INT");

                    b.HasKey("ID");

                    b.ToTable("Launchpads", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CurrentStatus = 0,
                            Location = "Cape Canaveral",
                            MaxSupportedWeight = 0
                        },
                        new
                        {
                            ID = 2,
                            CurrentStatus = 0,
                            Location = "Vandenberg",
                            MaxSupportedWeight = 0
                        });
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INT");

                    b.HasKey("ID");

                    b.ToTable("Managers", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 6
                        },
                        new
                        {
                            ID = 7
                        });
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("INT");

                    b.Property<int>("FK_CelestialID")
                        .HasColumnType("INT");

                    b.Property<int?>("FK_CrewID")
                        .HasColumnType("INT");

                    b.Property<int>("FK_ManagerID")
                        .HasColumnType("INT");

                    b.Property<int>("FK_RocketID")
                        .HasColumnType("INT");

                    b.Property<int?>("FK_launchpadID")
                        .HasColumnType("INT");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("ID");

                    b.HasIndex("FK_CelestialID");

                    b.HasIndex("FK_CrewID");

                    b.HasIndex("FK_ManagerID");

                    b.HasIndex("FK_RocketID")
                        .IsUnique();

                    b.HasIndex("FK_launchpadID");

                    b.ToTable("Missions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CurrentStatus = 5,
                            Duration = 8,
                            FK_CelestialID = 3,
                            FK_CrewID = 1,
                            FK_ManagerID = 7,
                            FK_RocketID = 2,
                            FK_launchpadID = 1,
                            LaunchDate = new DateOnly(1969, 7, 16),
                            Name = "Apollo 11",
                            Type = "Lunar Landing"
                        },
                        new
                        {
                            ID = 2,
                            CurrentStatus = 3,
                            Duration = 300,
                            FK_CelestialID = 2,
                            FK_CrewID = 2,
                            FK_ManagerID = 6,
                            FK_RocketID = 1,
                            FK_launchpadID = 2,
                            LaunchDate = new DateOnly(2030, 3, 1),
                            Name = "Mars Explorer",
                            Type = "Mars Mission"
                        });
                });

            modelBuilder.Entity("Rocket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("INT");

                    b.Property<int>("FuelCapacity")
                        .HasColumnType("INT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("NumberOfStages")
                        .HasColumnType("INT");

                    b.Property<int?>("TotalWeight")
                        .HasColumnType("INT");

                    b.HasKey("ID");

                    b.ToTable("Rockets", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CrewCapacity = 7,
                            FuelCapacity = 500000,
                            ModelName = "Falcon 9",
                            NumberOfStages = 2,
                            TotalWeight = 549000
                        },
                        new
                        {
                            ID = 2,
                            CrewCapacity = 3,
                            FuelCapacity = 950000,
                            ModelName = "Saturn V",
                            NumberOfStages = 3,
                            TotalWeight = 2970000
                        });
                });

            modelBuilder.Entity("Scientist", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Scientists", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 4,
                            Specialty = "Astrophysics",
                            Title = "Dr."
                        },
                        new
                        {
                            ID = 5,
                            Specialty = "Planetary Science",
                            Title = "Dr."
                        });
                });

            modelBuilder.Entity("Astronaut", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithOne("Astronaut")
                        .HasForeignKey("Astronaut", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CelestialBody", b =>
                {
                    b.HasOne("CelestialBody", "ParentPlanet")
                        .WithMany("Moons")
                        .HasForeignKey("FK_ParentPlanetID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentPlanet");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.HasOne("Manager", "manager")
                        .WithMany("Departments")
                        .HasForeignKey("FK_managerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Joint_Astronaut_Crew", b =>
                {
                    b.HasOne("Astronaut", "astronaut")
                        .WithMany("joint_Astronaut_Crew")
                        .HasForeignKey("AstronautID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crew", "crew")
                        .WithMany("joint_Astronaut_Crew")
                        .HasForeignKey("CrewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("astronaut");

                    b.Navigation("crew");
                });

            modelBuilder.Entity("Joint_Scientist_Mission", b =>
                {
                    b.HasOne("Mission", "mission")
                        .WithMany("joint_scientist_missions")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientist", "scientist")
                        .WithMany("joint_scientist_missions")
                        .HasForeignKey("ScientistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mission");

                    b.Navigation("scientist");
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithOne("Manager")
                        .HasForeignKey("Manager", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.HasOne("CelestialBody", "celestialBody")
                        .WithMany("Missions")
                        .HasForeignKey("FK_CelestialID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crew", "crew")
                        .WithMany("Missions")
                        .HasForeignKey("FK_CrewID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Manager", "manager")
                        .WithMany("Missions")
                        .HasForeignKey("FK_ManagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rocket", "AssignedRocket")
                        .WithOne("Mission")
                        .HasForeignKey("Mission", "FK_RocketID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Launchpad", "launchpad")
                        .WithMany("Missions")
                        .HasForeignKey("FK_launchpadID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedRocket");

                    b.Navigation("celestialBody");

                    b.Navigation("crew");

                    b.Navigation("launchpad");

                    b.Navigation("manager");
                });

            modelBuilder.Entity("Scientist", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithOne("Scientist")
                        .HasForeignKey("Scientist", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Astronaut", b =>
                {
                    b.Navigation("joint_Astronaut_Crew");
                });

            modelBuilder.Entity("CelestialBody", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("Moons");
                });

            modelBuilder.Entity("Crew", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("joint_Astronaut_Crew");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Astronaut");

                    b.Navigation("Manager");

                    b.Navigation("Scientist");
                });

            modelBuilder.Entity("Launchpad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Missions");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.Navigation("joint_scientist_missions");
                });

            modelBuilder.Entity("Rocket", b =>
                {
                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Scientist", b =>
                {
                    b.Navigation("joint_scientist_missions");
                });
#pragma warning restore 612, 618
        }
    }
}
