services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Abcd123456!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 4g

  webapi:
    build:
      context: ./SourceCode/AarhusSpaceProgram
      dockerfile: Dockerfile
    container_name: webapi
    restart: unless-stopped
    ports:
      - "5062:5062"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5062
      ConnectionStrings__DefaultConnection: "Data Source=sqlserver;Initial Catalog=AarhusSpaceProgram;User ID=sa;Password=Abcd123456!;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True;Authentication=SqlPassword;Application Intent=ReadWrite;"
      MongoDB__ConnectionString: "mongodb://root:example@mongo:27017"
      Serilog__WriteTo__0__Args__databaseUrl: "mongodb://root:example@mongodb:27017/AarhusSpaceLogs"
      JWT__Issuer: "AarhusSpaceProgram"
      JWT__Audience: "AarhusSpaceProgramUsers"
      JWT__SigningKey: THIS_IS_A_VERY_LONG_SECRET_KEY_AT_LEAST_32_CHARS_LONG_12345
    depends_on:
      - sqlserver
      - mongo

  backgroundservice:
    build:
      context: ./SourceCode/MissionLogService
      dockerfile: Dockerfile
    container_name: backgroundservice
    restart: unless-stopped
    environment:
      MongoDB__ConnectionString: "mongodb://root:example@mongo:27017"
      WebApi__BaseUrl: "http://webapi:5062"
    depends_on:
      - mongo
      - webapi

volumes:
  sqlserver_data: